apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: latam-challenge-service
  annotations:
    run.googleapis.com/vpc-access-connector: projects/latam-challenge-ml-440920/locations/us-east1/connectors/my-connector
    run.googleapis.com/vpc-access-egress: all
spec:
  template:
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/latam-challenge-ml-440920/latam-challenge-daniel-ospina/latam-challenge-daniel-ospina:latest
          env:
            - name: dataset_id
              value: challenge_latam
            - name: MODELS_BUCKET_NAME
              value: models_challenge_daniel_ospina
            - name: project_id
              value: latam-challenge-ml-440920
            - name: table_id
              value: training_metrics
            - name: REDIS_HOST
              value: 10.2.136.123
          ports:
            - containerPort: 8080